### PR TITLE
Add psutil to test dependencies

### PR DESCRIPTION
**Pull request by arjkesh**
*GitHub Issue #, if available:*

Note: If merging this PR should also close the associated Issue, please also add that Issue # to the Linked Issues section on the right. 

### Description
- All PRs currently blocked because of psutil import issue. Add psutil as test dependency to unblock quick checks

### Tests run
- Tests in PR

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by tejaschumbalkar — COMMENTED** [review]
Does the TF inference [requirements.txt](https://github.com/aws/deep-learning-containers/blob/master/test/sagemaker_tests/tensorflow/inference/requirements.txt) needs `psutil` as well?

**Review by tejaschumbalkar — APPROVED** [review]

**Review by SergTogul — APPROVED** [review]
Do we need to pin it or we're ok with unpinned dependency?

**Comment by ahsan-z-khan** [comment]
We have removed `psutil` from the required package in the sagemaker SDK. Can you try to pull sagemaker 2.59.0 and test it?

**Comment by arjkesh** [comment]
This appears to be a bug in sagemaker pysdk that was fixed. Tests are passing in other PRs so we should be able to close this out.

**Pull request closed without merging**
