### PR TITLE
[test]Update requirements.txt

### PR DESCRIPTION
**Pull request by ChaiBapchya**
Add junit-xml

*Issue #, if available:*
Installing `requirements.txt` & running `testrunner.py` throws this error
```
python3 test/testrunner.py
Traceback (most recent call last):
  File "test/testrunner.py", line 16, in <module>
    from test_utils import sagemaker as sm_utils
  File "/home/ubuntu/deep-learning-containers/test/test_utils/sagemaker.py", line 11, in <module>
    from junit_xml import TestSuite, TestCase
ModuleNotFoundError: No module named 'junit_xml'
```

## Checklist
- [x] I've prepended PR tag with frameworks/job this applies to : [mxnet, tensorflow, pytorch] | [build] | [test] | [build, test] | [ec2, ecs, eks, sagemaker]
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [x] (If applicable) I've documented below the tests I've run on the DLC image
- [x] (If applicable) I've reviewed the licenses of updated and new binaries and their dependencies to make sure all licenses are on the Apache Software Foundation Third Party License Policy Category A or Category B license list.  See [https://www.apache.org/legal/resolved.html](https://www.apache.org/legal/resolved.html).
- [x] (If applicable) I've scanned the updated and new binaries to make sure they do not have vulnerabilities associated with them.

*Tests run:* 
```
python3 test/testrunner.py
```

*DLC image/dockerfile:*

*Additional context:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by TusharKanekiDey** [comment]
Thanks for creating this PR.

**Comment by ChaiBapchya** [comment]
It fails TF CI with EIA related error. Any idea if this is flaky? @TusharKanekiDey

**Comment by TusharKanekiDey** [comment]
@ChaiBapchya It is not due to EI Issue.
According to the logs-
`
[91mcannot create /etc/apt/sources.list: Interrupted system call
--
950 | ·[0m
951 | The command '/bin/sh -c apt-get update  && apt-get -y install --no-install-recommends     curl     gnupg2     ca-certificates     emacs     git     wget     build-essential     vim  && curl -s http://nginx.org/keys/nginx_signing.key \| apt-key add -  && echo 'deb http://nginx.org/packages/ubuntu/ bionic nginx' >> /etc/apt/sources.list  && apt-get update  && apt-get -y install --no-install-recommends     nginx     nginx-module-njs  && apt-get clean  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 2
952 | Traceback (most recent call last):
953 | File "src/main.py", line 57, in <module>
954 | image_builder(args.buildspec)
955 | File "/codebuild/output/src056553169/src/github.com/aws/deep-learning-containers/src/image_builder.py", line 207, in image_builder
956 | raise Exception("Build failed")
957 | Exception: Build failed
`
This is not a common issue. Restarted the test for now.

**Comment by ChaiBapchya** [comment]
@TusharKanekiDey curious why this wasn't caught in CI? Doesn't CI use requirements.txt to build the environment?

**Pull request merged**
