### PR TITLE
[PT] [build] [sagemaker] Install libboost, autoreconf

### PR DESCRIPTION
**Pull request by ChaiBapchya**
*Issue #, if available:*

For latest PT DLC i.e. py3 cu101 1.6.0

## Checklist
- [x] I've prepended PR tag with frameworks/job this applies to : [mxnet, tensorflow, pytorch] | [ei/neuron] | [build] | [test] | [benchmark] | [ec2, ecs, eks, sagemaker]
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [x] (If applicable) I've documented below the tests I've run on the DLC image
- [x] (If applicable) I've reviewed the licenses of updated and new binaries and their dependencies to make sure all licenses are on the Apache Software Foundation Third Party License Policy Category A or Category B license list.  See [https://www.apache.org/legal/resolved.html](https://www.apache.org/legal/resolved.html).
- [x] (If applicable) I've scanned the updated and new binaries to make sure they do not have vulnerabilities associated with them.

## Reviewer Checklist
* For reviewer, before merging, please cross-check:
- [ ] I've verified the code change on the config file mentioned above has already been reverted

*Description:*

Why added?
- libboost is a C++ boost library. It complements the C++ standard libraries. It is used in various applications. Details: [boost.org](https://www.boost.org/)
Specifically, distributed training libraries can leverage libboost for inter-process communication utility.

- autoreconf is library that's useful for building/installing software in general. It helps in configuring packages/libraries in shell.
Details: [gnu.org/autoreconf/manual](https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/autoreconf-Invocation.html)

*Tests run:*
dlc-sagemaker & dlc-ec2 tests for pytorch.

*DLC image/dockerfile:* 1.6.0 PT GPU py36

*Additional context:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
capacity issue.. and it shouldn't be erroring out silently..
```
CapacityError: Unable to provision requested ML compute capacity. Please retry using a different ML instance type.
```

**Comment by ChaiBapchya** [comment]
@saimidu Thanks for retriggering. PR passed for both sagemaker & sagemaker-local
Good to revert?

**Comment by saimidu** [comment]
The tests seem to have run correctly this time around. Please go ahead and revert the change first, and then update branch next. I will approve.

**Comment by arjkesh** [comment]
Hi @ChaiBapchya -- are there any explicit sanity or functional tests we can add as a result of adding these packages? Right now it seems like all we're testing is that it doesn't break existing functional tests, but new libraries added to Dockerfiles should be accompanied by tests

**Comment by ChaiBapchya** [comment]
Discussed offline, closing this PR due to no direct requirement for consuming these 2 packages in the containers at the moment.

**Pull request closed without merging**
