### PR TITLE
[tensorflow] | [build, test] | [ec2, ecs, eks, sagemaker] Update smexperiment version to 0.1.14 for tf22 cu101 and cpu Dockerfile

### PR DESCRIPTION
**Pull request by YYStreet**
## Checklist
- [x] I've prepended PR tag with frameworks/job this applies to : [tensorflow] | [build, test] | [ec2, ecs, eks, sagemaker]

*Description:*
Update smexperiments for cu101 and cpu tf2 py3 image to 0.1.14, keep it consistent with cu102 gpu image

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by YYStreet** [comment]
Should it be considered that to unset the fixed version number for smexperiments?

**Comment by TusharKanekiDey** [comment]
> Should it be considered that to unset the fixed version number for smexperiments?

Can you check this with @danabens? In PT PR, It has written it in this way -  `sagemaker-experiments==0.* \` which we can keep for all the dockerfiles.

**Comment by YYStreet** [comment]
> > Should it be considered that to unset the fixed version number for smexperiments?
> 
> Can you check this with @danabens? In PT PR, It has written it in this way - `sagemaker-experiments==0.* \` which we can keep for all the dockerfiles.

Checked with him. Will use the pattern you are suggesting

**Comment by YYStreet** [comment]
Close in favor of https://github.com/aws/deep-learning-containers/pull/439

**Pull request closed without merging**
