### PR TITLE
[pytorch][ei][build] add default infererence handler for pytorch eia 1.5.1

### PR DESCRIPTION
**Pull request by jbarz1**
*Issue #, if available:*

## PR Checklist
- [x] I've prepended PR tag with frameworks/job this applies to : [mxnet, tensorflow, pytorch] | [ei/neuron] | [build] | [test] | [benchmark] | [ec2, ecs, eks, sagemaker]
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [x] (If applicable) I've documented below the tests I've run on the DLC image
- [ ] (If applicable) I've reviewed the licenses of updated and new binaries and their dependencies to make sure all licenses are on the Apache Software Foundation Third Party License Policy Category A or Category B license list.  See [https://www.apache.org/legal/resolved.html](https://www.apache.org/legal/resolved.html).
- [ ] (If applicable) I've scanned the updated and new binaries to make sure they do not have vulnerabilities associated with them.

## Pytest Marker Checklist
- [ ] (If applicable) I have added the marker `@pytest.mark.model("<model-type>")` to the new tests which I have added, to specify the Deep Learning model that is used in the test (use `"N/A"` if the test doesn't use a model)
- [ ] (If applicable) I have added the marker `@pytest.mark.integration("<feature-being-tested>")` to the new tests which I have added, to specify the feature that will be tested
- [ ] (If applicable) I have added the marker `@pytest.mark.multinode(<integer-num-nodes>)` to the new tests which I have added, to specify the number of nodes used on a multi-node test
- [ ] (If applicable) I have added the marker `@pytest.mark.processor(<"cpu"/"gpu"/"eia"/"neuron">)` to the new tests which I have added, if a test is specifically applicable to only one processor type

#### EIA/NEURON Checklist
* When creating a PR:
- [x] I've modified `src/config/build_config.py` in my PR branch by setting `ENABLE_EI_MODE = True` or `ENABLE_NEURON_MODE = True`
* When PR is reviewed and ready to be merged:
- [x] I've reverted the code change on the config file mentioned above

## Reviewer Checklist
* For reviewer, before merging, please cross-check:
- [x] I've verified the code change on the config file mentioned above has already been reverted

*Description:*
add default infererence handler for pytorch eia 1.5.1.

We expect the customer to provide their own inference handlers according to this documentation. Thats why we don't provide a default handler in the [sagemaker-pytorch-inference-toolkit](https://github.com/aws/sagemaker-pytorch-inference-toolkit)

https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html#create-a-pytorchmodel-object
```
If you are using PyTorch Elastic Inference 1.5.1, you should provide model_fn like below in your script to use new api attach_eia. 

Reference can be find in Elastic Inference documentation.
```

However we need a default handler anyway because we want to add a default image in the sagemaker configuration.
https://github.com/aws/sagemaker-python-sdk/pull/2119
This PR is needed for tests to work when making the sagemaker sdk change

*Tests run:*

*DLC image/dockerfile:*

pytorch/inference/docker/1.5.1/py3/Dockerfile.eia

*Additional context:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jbarz1** [comment]
some unrelated tests are failing to pull from docker for some reason. E.g.

```

Step 1/26 : FROM ubuntu:18.04
--
918 |  
919 |  
920 | unauthorized: authentication required


```

**Comment by tejaschumbalkar** [comment]
> some unrelated tests are failing to pull from docker for some reason. E.g.
> 
> ```
> 
> Step 1/26 : FROM ubuntu:18.04
> --
> 918 |  
> 919 |  
> 920 | unauthorized: authentication required
> ```

We saw an intermittent failure during docker login. Subsequent builds should resolve the failure.

**Comment by jbarz1** [comment]
unrelated tensorflow eia failing. I think we can ignore that.

```
--2021-06-08 14:26:12--  https://amazonei-tensorflow.s3.amazonaws.com/tensorflow-serving/v1.15/ubuntu/archive/tensorflow-serving-1-15-2-ubuntu-ei-1-5.tar.gz
Resolving amazonei-tensorflow.s3.amazonaws.com (amazonei-tensorflow.s3.amazonaws.com)... 
52.217.109.116
Connecting to amazonei-tensorflow.s3.amazonaws.com (amazonei-tensorflow.s3.amazonaws.com)|52.217.109.116|:443... 
connected.
HTTP request sent, awaiting response... 
403 Forbidden
```

**Review by saimidu — COMMENTED** [review]
Please add an explanation about why this new `default_inference_handler.py` needs to be inserted into the EI DLC image to override the existing default_inference_handler from the `sagemaker-pytorch-inference-toolkit` package.

**Review by saimidu — COMMENTED** [review]
Soft Approved. Will approve and merge once comments are addressed, and the build config changes are reverted.

**Comment by jbarz1** [comment]
hey Sai,

I will cancel this PR.

We expect the customer to provide their own inference handlers according to this documentation.

https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html#create-a-pytorchmodel-object

```
If you are using PyTorch Elastic Inference 1.5.1, you should provide model_fn like below in your script to use new api attach_eia. 

Reference can be find in Elastic Inference documentation.
```

**Comment by jbarz1** [comment]
just realized that the reason for this PR, is so that we can add a default image in the sagemaker configuration.

https://github.com/aws/sagemaker-python-sdk/pull/2119

**Review by saimidu — APPROVED** [review]

**Comment by jbarz1** [comment]
error is unrelated,

framework version 1.8

**Pull request merged**
