### PR TITLE
[PyTorch] Update sagemaker-pytorch-inference to 2.0.16

### PR DESCRIPTION
**Pull request by humanzz**
*GitHub Issue #, if available:* #2509

**Note**: 
- If merging this PR should also close the associated Issue, please also add that Issue # to the Linked Issues section on the right. 

- All PR's are checked weekly for staleness. This PR will be closed if not updated in 30 days.

### Description
- Update all `SM_TOOLKIT_VERSION` (`sagemaker-pytorch-inference`) to `2.0.16` from `2.0.14`
- `sagemaker-pytorch-inference==2.0.16` reuses `requirements.txt` installation logic from `sagemaker-inference`
  - https://github.com/aws/sagemaker-pytorch-inference-toolkit/pull/150
  - https://github.com/aws/sagemaker-pytorch-inference-toolkit/releases/tag/v2.0.16
- `sagemaker-inference==1.10.0` updates `requirements.txt` installation logic to support installing dependencies from a CodeArtifact repository instead of public pypi index by specifying an environment variable `CA_REPOSITORY_ARN` 
  - https://github.com/aws/sagemaker-inference-toolkit/pull/130
  - https://github.com/aws/sagemaker-inference-toolkit/releases/tag/v1.10.0
- With those updates, SageMaker users should be able to specify `CA_REPOSITORY_ARN` for their models/inference endpoints, which would lead to `requirements.txt` dependencies being installed from the specified CodeArtifact repository

### Tests
- I wasn't able to follow through the contribution guide to identify/run relevant tests
- I built/published the containers to my own repo using
```
python src/main.py --buildspec pytorch/inference/buildspec.yml \
                   --framework pytorch \
                   --image_types inference \
                   --device_types cpu \
                   --py_versions py3
```

```
python src/main.py --buildspec pytorch/inference/buildspec-graviton.yml \
                   --framework pytorch \
                   --image_types inference \
                   --device_types cpu \
                   --py_versions py3
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by mohanasudhan — APPROVED** [review]

**Review by arjkesh — DISMISSED** [review]
SM remote/local tests pass on PT 2.0.1 inference images on [607320a](https://github.com/aws/deep-learning-containers/pull/3227/commits/607320a7da2f4aee3e5548c2e877a23870c0fda8)

**Review by arjkesh — APPROVED** [review]

**Pull request merged**
