### PR TITLE
[tensoflow][benchmark][test] Upgrading tensorflow serving api to 2.2.0

### PR DESCRIPTION
**Pull request by sboshin**
Removing unnecessary binary argument, It does nothing, Removing need to download unncessary binary from S3, fixing deprecated API calls in script. Upgraded serving_api to 2.2

*Issue #, if available:*

## Checklist
- [ ] I've prepended PR tag with frameworks/job this applies to : [mxnet, tensorflow, pytorch] | [build] | [test] | [build, test] | [ec2, ecs, eks, sagemaker]
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [ ] (If applicable) I've reviewed the licenses of updated and new binaries and their dependencies to make sure all licenses are on the Apache Software Foundation Third Party License Policy Category A or Category B license list.  See [https://www.apache.org/legal/resolved.html](https://www.apache.org/legal/resolved.html).
- [ ] (If applicable) I've scanned the updated and new binaries to make sure they do not have vulnerabilities associated with them.

#### EIA Checklist
* When creating a PR:
- [ ] I've modified ```src/config/build_config.py``` in my PR branch by setting ```ENABLE_EI_MODE = True```
* When PR is reviewed and ready to be merged:
- [ ] I've reverted the code change on the config file mentioned above

* For reviewer, before merging, please cross-check:
- [ ] I've verified the code change on the config file mentioned above has already been reverted

*Description:*

*Tests run:*

*DLC image/dockerfile:*

*Additional context:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sboshin** [comment]
Updated tf1 serving script to behave like tf2, So we don't need to pass in a binary argument.

**Comment by YYStreet** [comment]
> Updated tf1 serving script to behave like tf2, So we don't need to pass in a binary argument.

It seems currently tf1 script is identical with tf2 script. Should this script also be working for TF2.0 and TF2.1 inference?

**Comment by YYStreet** [comment]
> Updated tf1 serving script to behave like tf2, So we don't need to pass in a binary argument.

Here is a script provided by Akihil for TF2.0, with very minor difference https://github.com/aws/deep-learning-containers/blob/bbe004e8b98a1b3ab1b657674ce1a0b492b7acd6/test/dlc_tests/container_tests/bin/benchmark/tf20_serving_perf.py

**Comment by sboshin** [comment]
I think its okay to leave it separated. I don't remember the initial reason why we had it split.
Keeping it split will allow tf2 version to keep growing without impacting tf1 in the future

**Comment by YYStreet** [comment]
> I think its okay to leave it separated. I don't remember the initial reason why we had it split.
> Keeping it split will allow tf2 version to keep growing without impacting tf1 in the future.
> 
> I assume the minor difference came from using tf.contrib vs tf.compat. Its the same implementation just different API calls for compatibility

Could you give us an advice that if we should maintain different tf2 benchmark script for different tf2.x versions? If we still need to maintain the original test script as a copy for tf2.1, I can finish this part in another PR

**Comment by sboshin** [comment]
As the DLC testing is only testing the latest TF which will be 2.x, I don't see why we need a 2.0, 2.1, 2.2 script. And the current script should work for all versions of TF 2.x.
So the only split should be tf1 and tf2.

**Comment by YYStreet** [comment]
> As the DLC testing is only testing the latest TF which will be 2.x, I don't see why we need a 2.0, 2.1, 2.2 script. And the current script should work for all versions of TF 2.x.
> So the only split should be tf1 and tf2.

Thanks. Tests are all passing. I will revert the config change back and approve it.

**Pull request merged**
