### PR TITLE
Split HF inference and Training buildspecs

### PR DESCRIPTION
**Pull request by arjkesh**
*GitHub Issue #, if available:*

Note: If merging this PR should also close the associated Issue, please also add that Issue # to the Linked Issues section on the right. 

### Description
- Split HF inference buildspecs into inference specific buildspecs

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by hballuru — DISMISSED** [review]
Changes LGTM

**Comment by hballuru** [comment]
> Changes LGTM

But looks like sanity checks failed which I didn't notice earlier

**Review by tejaschumbalkar — COMMENTED** [review]
1. buildspec-2-6.yml has both training and inference
2. buildspec-1-6.yml can be deleted as well?

**Comment by arjkesh** [comment]
> 1. buildspec-2-6.yml has both training and inference
> 
>     2. buildspec-1-6.yml can be deleted as well?

Removed buildspec 2-6 - I don't see a buildspec 1-6 - am i missing something?

**Review by tejaschumbalkar — APPROVED** [review]

**Review by Vatshank — APPROVED** [review]

**Pull request merged**
