### PR TITLE
Run black -l 100 on all python files

### PR DESCRIPTION
**Pull request by arjkesh**
*GitHub Issue #, if available:*

**Note**: 
- If merging this PR should also close the associated Issue, please also add that Issue # to the Linked Issues section on the right. 

- All PR's are checked weekly for staleness. This PR will be closed if not updated in 30 days.

### Description
- Following guidelines from https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html and https://black.readthedocs.io/en/stable/faq.html#is-black-safe-to-use

### Tests run
- No tests added in this PR, they will be added in https://github.com/aws/deep-learning-containers/pull/2891

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by kace — APPROVED** [review]
Lgtm

**Review by josephevans — APPROVED** [review]
LGTM from smdebug team.

**Comment by Lokiiiiii** [comment]
LGTM from trcomp

**Review by gradientsky — DISMISSED** [review]
LGTM from autogluon

**Review by kace — APPROVED** [review]

**Pull request merged**
