### PR TITLE
[Tensorflow][Build]Resolve missing libcupti.so issue

### PR DESCRIPTION
**Pull request by Elizaaaaa**
*Issue #, if available:*
Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/openmpi/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64

## Checklist
- [x] I've prepended PR tag with frameworks/job this applies to : [tensorflow] | [test]  | [ec2]
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [ ] (If applicable) I've reviewed the licenses of updated and new binaries and their dependencies to make sure all licenses are on the Apache Software Foundation Third Party License Policy Category A or Category B license list.  See [https://www.apache.org/legal/resolved.html](https://www.apache.org/legal/resolved.html).
- [ ] (If applicable) I've scanned the updated and new binaries to make sure they do not have vulnerabilities associated with them.

*Description:*
With TensorBoard profiling turned on, we get this error on the new recently released TF2.2 container:
2020-06-03 01:47:51.923816: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcupti.so.10.1'; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/openmpi/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64

By this PR, we add the libcupti.so to the LD_LIBRARY_PATH to avoid the issue.

*Tests run:*
Local test on ec2

*DLC image/dockerfile:*
tensorflow/2.2.0/Dockefile.gpu

*Additional context:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by TusharKanekiDey** [comment]
Currently, in this PR, 
test_tensorflow_standalone_gpu, test_tensorflow_train_mnist_gpu and test_tensorflow_with_horovod_gpu are failing.

**Comment by rahul003** [comment]
Don't we need to do this for previous releases too?

**Comment by YYStreet** [comment]
> Don't we need to do this for previous releases too?

We will have a patch release for TF2.2 Images on next week. We will include this PR

**Comment by TusharKanekiDey** [comment]
Do we need a similar package for CUDA 10.2 ?

**Comment by YYStreet** [comment]
We changed the folder structure to support both cuda10.1 and cuda10.2 Images.

**Comment by rahul003** [comment]
Yes we should ensure 10.2 also has this

**Pull request closed without merging**
