### PR TITLE
Tf inference 2.7 mod

### PR DESCRIPTION
**Pull request by hsl89**
update tensorflow_model_server binary urls.

### CODE REVIEW

**Comment by arjkesh** [comment]
@hsl89 there are several conflicts with master here - can you resolve these? Please don't change the buildspec, just the dockerfile changes are necessary

**Comment by hsl89** [comment]
> @hsl89 there are several conflicts with master here - can you resolve these? Please don't change the buildspec, just the dockerfile changes are necessary

Do you mean to keep the buildspec from master?

**Comment by arjkesh** [comment]
> > @hsl89 there are several conflicts with master here - can you resolve these? Please don't change the buildspec, just the dockerfile changes are necessary
> 
> Do you mean to keep the buildspec from master?

yes

**Review by arjkesh — APPROVED** [review]

**Review by arjkesh — CHANGES_REQUESTED** [review]
I see that model server still prints out version is rc1. Adding this request changes to block accidental merge

**Comment by hsl89** [comment]
> I see that model server still prints out version is rc1. Adding this request changes to block accidental merge

This is possibly a bug in upstream https://github.com/tensorflow/serving/blob/r2.7/tensorflow_serving/model_servers/version.h#L30

**Review by arjkesh — APPROVED** [review]

**Pull request merged**
